--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from Y_样本_example_battle
]]


return
{
    ['award_show'] = {{2001,20},{4006,99},{8003,1}},
    ['close'] = '18:30:00',
    ['id'] = 10,
    ['level'] = 90,
    ['open'] = '18:00:00'
}