--[[
DO NOT MODITY!  Auto generated by py_exceltools

Y_样本_example.xlsx battle
]]


return
{
    ['award'] = {{1001,20},{3006,99},{7003,1}},
    ['close'] = '18:30:00',
    ['id'] = 10,
    ['level'] = 90,
    ['open'] = '18:00:00'
}