--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from example_activity
]]


return
{
    ['act_id'] = 10,
    ['award'] = {{1001,20},{3006,99},{7003,1}},
    ['close'] = '18:30:00',
    ['level'] = 90,
    ['open'] = '18:00:00'
}