--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/
]]

return
{
    ['level'] = 90,
    ['act_id'] = 10,
    ['open'] = '18:00:00',
    ['close'] = '18:30:00',
    ['award'] = {{1001,20,},{3006,99,},{7003,1,},},
}