--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/
]]

-- At 2017-06-24 16:43:09

return 
{
    {
        ['id'] = 1001,
        ['name'] = 'examp1001',
        ['attr'] = {{1,700,},{2,800,},{3,900,},},
    },
    {
        ['id'] = 1002,
        ['name'] = 'examp1002',
        ['attr'] = {{1,700,},{2,800,},{3,901,},},
    },
    {
        ['id'] = 1003,
        ['name'] = 'examp1003',
        ['attr'] = {{1,700,},{2,800,},{3,902,},},
    },
    {
        ['id'] = 1004,
        ['name'] = 'examp1004',
        ['attr'] = {{1,700,},{2,800,},{3,903,},},
    },
}