--[[
DO NOT MODITY!  Auto generated by py_exceltools
https://www.python.org/
http://www.python-excel.org/

from Y_样本_example_套装
]]


return
{
    {
        ['attr'] = {{1,700},{2,800},{3,900}},
        ['count'] = 2,
        ['id'] = 1,
        ['type'] = 1
    },
    {
        ['attr'] = {{1,700},{2,800},{3,901}},
        ['count'] = 4,
        ['id'] = 2,
        ['type'] = 3
    },
    {
        ['attr'] = {{1,700},{2,800},{3,902}},
        ['count'] = 6,
        ['id'] = 3,
        ['type'] = 5
    },
    {
        ['attr'] = {{1,700},{2,800},{3,903}},
        ['count'] = 8,
        ['id'] = 4,
        ['type'] = 7
    },
    {
        ['attr'] = {{1,700},{2,800},{3,904}},
        ['count'] = 10,
        ['id'] = 5,
        ['type'] = 9
    }
}